FROM jesperancinha/je-all-build-jdk-8:0.0.1

COPY ../bacalhao-a-bras-java $HOME/bacalhao-a-bras-java

COPY ../cataplana-de-ameijoas-clojure $HOME/cataplana-de-ameijoas-clojure

COPY ../filhos-de-natal-kotlin $HOME/filhos-de-natal-kotlin

COPY ../peixinhos-da-horta-scala $HOME/peixinhos-da-horta-scala

ENTRYPOINT ["entrypoint.sh"]